### ISSUE TITLE
What would be the way to set the versions numbering?

### ISSUE THREAD

**Issue by dprada** [uibcdf/OpenPharmacophore#5]
We should spend a while reading about how to set the names or numbers of the versions.

**Comment by Daniel-Ibarrola** [comment]
According to [semantic versioning](https://semver.org/), version numbers should be set like this:

Given a version number MAJOR.MINOR.PATCH, increment the:

1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards compatible manner, and
3. PATCH version when you make backwards compatible bug fixes.

Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

This could be a way to set the version numbers for OpenPharmacophore

**Comment by dprada** [comment]
Ok, so semantic versioning is probably the most extended policy to have a meaningful versioning strategy. Now, the question is, should we define at this moment what is version 1.0.0? Should we already design the sequence of goals to be accomplished to increase the minor version index?

I guess we have to try to draw a roadmap. Not 100% definitive, but it should be defined enough. Before defining projects and milestones in this repository, let's share a document or a discussion or a wiki. Probably a page in the wiki section can work as a shared notebook to include and sort concepts and goals to define a path to version 1.0.0.

**Comment by Daniel-Ibarrola** [comment]
Yes, we should definitively have a roadmap and a series of goals. We can start working on ideas of what should be incorporated into version 1.0.0.

**Comment by dprada** [comment]
Have a look at #11 and the wiki page [Roadmap to version 1.0.0](https://github.com/uibcdf/OpenPharmacophore/wiki/Roadmap-to-version-1.0.0) to implement it. If in your opinion this should be discussed using other tools, feel free to make suggestions or modifications.

**Comment by dprada** [comment]
The MOLSSI cookie-cutter includes the use of the python package versioneer. Let's follow the cookie-cutter to have a correct versioning system. See #2.

**Comment by dprada** [comment]
This issue can be closed already. It was fruitful already. The former ideas were already implemented.
