### ISSUE TITLE
Structure based pharmacophore and protein-ligand interactions

### ISSUE THREAD

**Issue by Daniel-Ibarrola** [uibcdf/OpenPharmacophore#57]
Currently structure based pharmacophores are extracted by using protein-ligand interactions using the library [plip](https://github.com/pharmai/plip), however plip was not conceived for pharmacophore extraction and it seems to have issues with hydrophobic features in the context of pharmacophores. Moreover, plip needs a pdb file to obtain the protein-ligand interactions  which is impractical and slow when extracting pharmacophores from a molecular dynamics trajectory. 

To solve this we need to search if there are any alternatives to plip.  If not, we'll probably have to implement the pharmacophore extraction from the protein-ligand complex.

**Comment by dprada** [comment]
I agree. Implementing the pharmacophore extraction here would entail some benefits in the future.

**Comment by orgw** [comment]
ACP4 (https://github.com/tsudalab/ACP4) provides code for extracting pharmacophores.
